apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "hiveserver.fullname" . }}
  labels:
{{ include "hiveserver.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "hiveserver.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "hiveserver.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      hostname: hiveserver
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.imagename }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: thrift
              containerPort: {{ .Values.service.targetPort.thrift }}
              protocol: TCP
            - name: ui
              containerPort: {{ .Values.service.targetPort.webUI }}
              protocol: TCP
          envFrom:
          - configMapRef:
              name: {{ template "hiveserver.fullname" . }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
