apiVersion: v1
kind: Service
metadata:
  name: {{ include "hiveserver.fullname" . }}
  labels:
{{ include "hiveserver.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: "{{ .Values.service.port.thrift }}"
    port: {{ .Values.service.port.thrift }}
    targetPort: {{ .Values.service.targetPort.thrift }}
    protocol: TCP
  - name: {{ .Values.service.port.webUI | quote }}
    port: {{ .Values.service.port.webUI }}
    targetPort: {{ .Values.service.targetPort.webUI }}
    protocol: TCP   
  selector:
    app.kubernetes.io/name: {{ include "hiveserver.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  {{- if .Values.serviceAffinity.sessionAffinity }}
  sessionAffinity: {{ .Values.serviceAffinity.sessionAffinity }}
  {{- if .Values.serviceAffinity.timeoutSeconds }}
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: {{ .Values.serviceAffinity.timeoutSeconds }}
  {{- end }}
  {{- end }}