apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "trino.coordinator" . }}
  labels:
    app: {{ template "trino.name" . }}
    chart: {{ template "trino.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: coordinator
spec:
  selector:
    matchLabels:
      app: {{ template "trino.name" . }}
      release: {{ .Release.Name }}
      component: coordinator
  template:
    metadata:
      labels:
        app: {{ template "trino.name" . }}
        release: {{ .Release.Name }}
        component: coordinator
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: {{ template "trino.coordinator" . }}
            items:
              - key: hive.properties
                path: catalog/hive.properties
              - key: node.properties
                path: node.properties
              - key: jvm.config
                path: jvm.config
              - key: config.properties
                path: config.properties
              - key: log.properties
                path: log.properties
      containers:
        - name: {{ .Chart.Name }}-coordinator
          image: "{{ .Values.image.registry }}/{{ .Values.image.imagename }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - mountPath: {{ .Values.server.config.path }}
              name: config-volume
          ports:
            - name: http-coord
              containerPort: {{ .Values.server.config.http.port }}
              protocol: TCP
          envFrom:
          - configMapRef:
              name: {{ template "trino.gateway" . }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
