# Default values for hive-metastore.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  registry: localhost:5000
  imagename: hive-server2
  tag: 3.2.2
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port:
    thrift: 8500
    webUI: 8502
  targetPort:
    thrift: 10000
    webUI: 10002

livenessProbe:
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3

readinessProbe:
  initialDelaySeconds: 45
  periodSeconds: 10
  timeoutSeconds: 1
  successThreshold: 1
  failureThreshold: 3
# We usually recommend not to specify default resources and to leave this as a conscious
# choice for the user. This also increases chances charts run on environments with little
# resources, such as Minikube. If you do want to specify resources, uncomment the following
# lines, adjust them as necessary, and remove the curly braces after 'resources:'.

resources: {}
  # limits:
  #   cpu: 0.8
  #   memory: 800Mi
  # requests:
  #   cpu: 0.2
  #   memory: 200Mi

nodeSelector: {}

tolerations: []

affinity: {}

serviceAffinity:
  sessionAffinity: ClientIP
  timeoutSeconds: 3

# values to put in config map
configs:
  SERVICE: 'hiveserver2'
  HIVE_METASTORE: hive-metastore:9083
  HIVE_SITE_CONF_hive_metastore_uris: thrift://hive-metastore:9083
