apiVersion: v1
kind: Service
metadata:
  name: {{ include "hive-metastore.fullname" . }}
  labels:
{{ include "hive-metastore.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: metastore
      protocol: TCP
      name: metastore
  selector:
    app.kubernetes.io/name: {{ include "hive-metastore.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  {{- if .Values.serviceAffinity.sessionAffinity }}
  sessionAffinity: {{ .Values.serviceAffinity.sessionAffinity }}
  {{- if .Values.serviceAffinity.timeoutSeconds }}
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: {{ .Values.serviceAffinity.timeoutSeconds }}
  {{- end }}
  {{- end }}