# Default values for hive-metastore.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  registry: localhost:5000
  imagename: hive-metastore
  tag: 3.2.2
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 9083

mysql:
  secretName: mysql-secret

# We usually recommend not to specify default resources and to leave this as a conscious
# choice for the user. This also increases chances charts run on environments with little
# resources, such as Minikube. If you do want to specify resources, uncomment the following
# lines, adjust them as necessary, and remove the curly braces after 'resources:'.

resources: {}
  # limits:
  #   cpu: 0.8
  #   memory: 800Mi
  # requests:
  #   cpu: 0.2
  #   memory: 200Mi

nodeSelector: {}

tolerations: []

affinity: {}

serviceAffinity:
  sessionAffinity: ClientIP
  timeoutSeconds: 3

# values to put in config map
configs:
  DB_TYPE: "mysql"
  CONNECTION_URI: 'jdbc:mysql://mysql.default.svc.cluster.local:3306/metastore_db?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false'
  CONNECTION_USER: root
  CONNECTION_DRIVER: "com.mysql.jdbc.Driver"
  HIVE_WAREHOUSE_DIR: "/"
  SERVICE: 'metastore'
  METASTORE_SITE_CONF_javax_jdo_option_ConnectionURL: 'jdbc:mysql://mysql.default.svc.cluster.local:3306/metastore_db?useSSL=false'